data-dir=/var/lib/monero/bitmonero
prune-blockchain=1
sync-pruned-blocks=1
check-updates=disabled
enable-dns-blocklist=1
enforce-dns-checkpointing=1
log-file=/var/log/monero/monero.log
log-level=0
max-log-file-size=2147483648
rpc-restricted-bind-ip=0.0.0.0
rpc-restricted-bind-port=18089
zmq-pub=tcp://127.0.0.1:18083
max-txpool-weight=2684354560
out-peers=36
in-peers=64
add-priority-node=p2pmd.xmrvsbeast.com:18080
add-priority-node=nodes.hashvault.pro:18080
add-priority-node=node.supportxmr.com:18080
add-priority-node=node.monerodevs.org:18080
add-priority-node=node2.monerodevs.org:18080
add-priority-node=node3.monerodevs.org:18080
add-priority-node=node.sethforprivacy.com:18080
limit-rate-up=1048576
limit-rate-down=1048576
disable-rpc-ban=1